server:
  port: 8090


app:
  db-oracle-pvso:
    datasource:
      class-driver: oracle.jdbc.OracleDriver
      username: FSBS
      password: ppS9Lx
      url: jdbc:oracle:thin:@//dm1-scan.int.fss.ru:1521/elsedutc
  db-pg-test:
    datasource:
      class-driver: org.postgresql.Driver
      username: postgres
      password: serg6363
      url: jdbc:postgresql://localhost:5435/cybertester


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: none


#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:database/schema.sql

